development:
  dialect: postgres
  database: postgres
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

development:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5433/postgres"}}

test:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5433/postgres"}}